### ISSUE TITLE
E/StorageException: StorageException has occurred.

### ISSUE THREAD

**Issue by malloryjanecs** [Blak3Nick/UMGC.Team3#13]
From what I can find online, it is linked to not finding a something in FireBase. In one instance, a user was trying to access an imagine in FB storage ending in ".jpeg", but their code was looking for ".png". 

Need to find what the code is trying to do and try to fix it.

![image](https://user-images.githubusercontent.com/67796709/123460920-5f072500-d5b6-11eb-8d5e-6e86632c46d1.png)

**Comment by malloryjanecs** [comment]
This could also be due to lack of permissions since I'm not logged into FireBase with access permissions. If @Blak3Nick doesn't receive this error, it may be a permissions issue. I found this as well.
![image](https://user-images.githubusercontent.com/67796709/123461118-a8577480-d5b6-11eb-91cf-54ca02ecbda4.png)

**Comment by alayne777** [comment]
![image](https://user-images.githubusercontent.com/86016547/124053545-76974100-d9ee-11eb-8d1e-aacc6414580a.png)
I am getting the same error on my end.
