### ISSUE TITLE
When logging out, NullPointerException happens

### ISSUE THREAD

**Issue by malloryjanecs** [Blak3Nick/UMGC.Team3#27]
I believe this is because MainActivity is still running, so when I log out, the onCreate() method is still attempting to do things and causes an error. The NullPointerException error is happening on line 101 in MainActivity.java

Specifically, I think it's trying to grab a userId and create a DocumentReference based on the userId. However, since no userId exists when logging out, it can't create the DocumentReference and in-turn the reference is Null, causing the documentSnapshot.exists() to be null and throw the error.

If anyone has any ideas about how to fix it or if you think I'm way off-base, let me know! Otherwise, I will play around with it and see if I can make it work.

**Comment by Blak3Nick** [comment]
What about simply wrapping that call in a try-catch block? Since there is no need for the reference if they are logged out, that solution seems pretty simple.

**Comment by malloryjanecs** [comment]
@Blak3Nick  - This is the bug I was saying I'll be uploading the fix to hopefully today. Since it's a fatal exception, a try-catch doesn't stop the program from catching, although it did help me pinpoint it.
