### ISSUE TITLE
Weight Increase or Decrease based on RPE

### ISSUE THREAD

**Issue by Blak3Nick** [Blak3Nick/UMGC.Team3#9]
The current workout plan should be updated with new weights when the user inputs an RPE greater than 2 over target RPE or less than 2 under the target RPE. RPE stands for rate of perceived effort and is on a 1-10 scale. Each set has a target RPE assigned to it. If the user has a target of 7 and they input 9 this means it was 2 units more difficult than intended. The weights for that set should be lowered accordingly. Either a percentage or flat decrease should be considered. A percentage decrease is problematic because weights are typically in 5 pound increments at the gym. In the reverse case where a user's reported RPE is less than 2 under the target RPE, the weights for that set should be increased. Subsequent sets should also be increased or decreased for that exercise. So if the user reports under for set number 1, then that set plus any remaining sets for that exercise should be increased by the factor.

**Comment by alayne777** [comment]
Need to also add in tooltip so user knows what RPE is.

**Comment by Blak3Nick** [comment]
The tooltip is included in the screen which explains to the user what to input
